# Generated by Django 3.2.14 on 2022-07-19 12:12

from django.db import migrations, models
import django.db.models.expressions
import fullctl.django.fields.service_bridge


class Migration(migrations.Migration):

    dependencies = [
        ('django_devicectl', '0003_device_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='reference',
            field=fullctl.django.fields.service_bridge.ReferencedObjectCharField(blank=True, bridge_type='device', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(django.db.models.expressions.F('reference'), name='device_reference'),
        ),
    ]
