# Generated by Django 3.2.14 on 2022-07-19 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_devicectl", "0005_facility"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Device is located in this facility",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="django_devicectl.facility",
            ),
        ),
    ]
