# Generated by Django 3.2.14 on 2022-07-20 15:43

import django_countries.fields
import fullctl.django.fields.service_bridge
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_devicectl", "0007_rel_backref"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="address1",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Address 1"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="address2",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Address 2"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="city",
            field=models.CharField(blank=True, max_length=255, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="facility",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="floor",
            field=models.CharField(blank=True, max_length=255, verbose_name="Floor"),
        ),
        migrations.AddField(
            model_name="facility",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="reference",
            field=fullctl.django.fields.service_bridge.ReferencedObjectCharField(
                blank=True, bridge_type="facility", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="state",
            field=models.CharField(blank=True, max_length=255, verbose_name="State"),
        ),
        migrations.AddField(
            model_name="facility",
            name="suite",
            field=models.CharField(blank=True, max_length=255, verbose_name="Suite"),
        ),
        migrations.AddField(
            model_name="facility",
            name="zipcode",
            field=models.CharField(blank=True, max_length=48, verbose_name="Zip-Code"),
        ),
    ]
