# Generated by Django 3.2.14 on 2022-08-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_devicectl", "0008_facility_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="reference_is_sot",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="reference_is_sot",
            field=models.BooleanField(default=True),
        ),
    ]
