# Generated by Django 3.2.14 on 2022-08-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_devicectl", "0009_reference_is_sot"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="slug",
            field=models.SlugField(default="fac-1", max_length=64),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="facility",
            constraint=models.UniqueConstraint(
                fields=("instance", "slug"), name="unique_slug_instance_pair"
            ),
        ),
    ]
