# Generated by Django 3.2.15 on 2022-09-09 09:13

import django.db.models.deletion
import django.db.models.manager
import django_handleref.models
import netfields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_devicectl", "0010_auto_20220804_1039"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="type",
            field=models.CharField(
                help_text="Type of device (software)", max_length=255
            ),
        ),
        migrations.CreateModel(
            name="PortInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created",
                    django_handleref.models.CreatedDateTimeField(
                        auto_now_add=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated",
                    django_handleref.models.UpdatedDateTimeField(
                        auto_now=True, verbose_name="Updated"
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Ok"),
                            ("pending", "Pending"),
                            ("deactivated", "Deactivated"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="ok",
                        max_length=12,
                    ),
                ),
                (
                    "ip_address_4",
                    netfields.fields.InetAddressField(
                        blank=True, max_length=39, null=True
                    ),
                ),
                (
                    "ip_address_6",
                    netfields.fields.InetAddressField(
                        blank=True, max_length=39, null=True
                    ),
                ),
                ("is_management", models.BooleanField(default=False)),
                ("is_routeserver_peer", models.BooleanField(default=False)),
                ("speed", models.PositiveIntegerField(default=0)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="port_infos",
                        to="django_fullctl.instance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Port information",
                "verbose_name_plural": "Port information",
                "db_table": "devicectl_port_info",
                "unique_together": {("instance", "ip_address_4", "ip_address_6")},
            },
            managers=[
                ("handleref", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Port",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created",
                    django_handleref.models.CreatedDateTimeField(
                        auto_now_add=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated",
                    django_handleref.models.UpdatedDateTimeField(
                        auto_now=True, verbose_name="Updated"
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Ok"),
                            ("pending", "Pending"),
                            ("deactivated", "Deactivated"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="ok",
                        max_length=12,
                    ),
                ),
                (
                    "port_info",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="port",
                        to="django_devicectl.portinfo",
                    ),
                ),
                (
                    "virtual_port",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ports",
                        to="django_devicectl.virtualport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Port",
                "verbose_name_plural": "Ports",
                "db_table": "devicectl_port",
            },
            managers=[
                ("handleref", django.db.models.manager.Manager()),
            ],
        ),
    ]
