# Generated by Django 3.2.15 on 2022-09-19 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_devicectl", "0012_auto_20220919_1441"),
    ]

    operations = [
        migrations.AlterField(
            model_name="port",
            name="port_info",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="port",
                to="django_devicectl.portinfo",
            ),
        ),
    ]
