# Generated by Django 3.2.15 on 2022-09-28 09:25

import fullctl.django.fields.service_bridge
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_devicectl", "0015_apidocs"),
    ]

    operations = [
        migrations.AddField(
            model_name="portinfo",
            name="reference",
            field=fullctl.django.fields.service_bridge.ReferencedObjectCharField(
                blank=True,
                bridge_type="port_info",
                help_text="Remote reference id",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="portinfo",
            name="reference_is_sot",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="virtualport",
            name="reference",
            field=fullctl.django.fields.service_bridge.ReferencedObjectCharField(
                blank=True,
                bridge_type="virtual_port",
                help_text="Remote reference id",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="virtualport",
            name="reference_is_sot",
            field=models.BooleanField(default=True),
        ),
    ]
