# Generated by Django 3.2.15 on 2022-09-28 10:51

import django.db.models.deletion
import django.db.models.manager
import django_handleref.models
import fullctl.django.fields.service_bridge
import netfields.fields
from django.db import migrations, models


def migrate_ips(apps, schema_editor):

    PortInfo = apps.get_model("django_devicectl", "PortInfo")
    IPAddress = apps.get_model("django_devicectl", "IPAddress")

    for port_info in PortInfo.handleref.all():
        if port_info.ip_address_4:
            IPAddress.handleref.create(
                port_info=port_info,
                instance=port_info.instance,
                address=port_info.ip_address_4,
            )
        if port_info.ip_address_6:
            IPAddress.handleref.create(
                port_info=port_info,
                instance=port_info.instance,
                address=port_info.ip_address_6,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("django_devicectl", "0016_auto_20220928_0925"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="portinfo",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="portinfo",
            name="reference",
        ),
        migrations.RemoveField(
            model_name="portinfo",
            name="reference_is_sot",
        ),
        migrations.CreateModel(
            name="IPAddress",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created",
                    django_handleref.models.CreatedDateTimeField(
                        auto_now_add=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated",
                    django_handleref.models.UpdatedDateTimeField(
                        auto_now=True, verbose_name="Updated"
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Ok"),
                            ("pending", "Pending"),
                            ("deactivated", "Deactivated"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="ok",
                        max_length=12,
                    ),
                ),
                ("reference_is_sot", models.BooleanField(default=True)),
                ("address", netfields.fields.InetAddressField(max_length=39)),
                (
                    "reference",
                    fullctl.django.fields.service_bridge.ReferencedObjectCharField(
                        blank=True,
                        bridge_type="ip",
                        help_text="Remove reference id",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ips",
                        to="django_fullctl.instance",
                    ),
                ),
                (
                    "port_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ips",
                        to="django_devicectl.portinfo",
                    ),
                ),
            ],
            options={
                "db_table": "devicectl_ip",
                "unique_together": {("instance", "address")},
            },
            managers=[
                ("handleref", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(migrate_ips, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="portinfo",
            name="ip_address_4",
        ),
        migrations.RemoveField(
            model_name="portinfo",
            name="ip_address_6",
        ),
    ]
