# Generated by Django 3.2.15 on 2023-04-19 15:19

import fullctl.django.fields.service_bridge
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_devicectl", "0019_deviceoperationalstatus_requestpeerctlsync"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceoperationalstatus",
            name="event",
            field=fullctl.django.fields.service_bridge.ReferencedObjectCharField(
                blank=True,
                bridge_type="event",
                help_text="auditCtl event reference",
                max_length=255,
                null=True,
            ),
        ),
    ]
