# Generated by Django 3.2.15 on 2023-05-11 09:12

from django.db import migrations


def create_missing_ports(apps, schema):
    VirtualPort = apps.get_model("django_devicectl", "VirtualPort")
    Port = apps.get_model("django_devicectl", "Port")
    PortInfo = apps.get_model("django_devicectl", "PortInfo")

    for virtual_port in VirtualPort.handleref.all():  #
        port, port_created = Port.handleref.get_or_create(virtual_port=virtual_port)
        if port_created:
            port_info = PortInfo.handleref.create(
                instance=virtual_port.logical_port.instance
            )
            port.port_info = port_info
            port.save()


class Migration(migrations.Migration):
    dependencies = [
        ("django_devicectl", "0021_alter_deviceoperationalstatus_error_message"),
    ]

    operations = [
        migrations.RunPython(create_missing_ports),
    ]
