# Generated by Django 3.2.19 on 2023-07-13 08:48

from django.db import migrations
import django.db.models.manager
import fullctl.django.inet.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_devicectl', '0026_auto_20230711_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualport',
            name='description',
            field=fullctl.django.inet.fields.DeviceDescriptionField(blank=True, max_length=255, null=True),
        ),
    ]
