# Generated by Django 3.2.20 on 2023-08-24 11:38

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_devicectl", "0027_auto_20230713_0848"),
    ]

    operations = [
        migrations.CreateModel(
            name="RenderTrafficGraphs",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_fullctl.task",),
            managers=[
                ("handleref", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="UpdateDeviceTrafficGraphs",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_fullctl.task",),
            managers=[
                ("handleref", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="UpdateIxctlIxTrafficGraphs",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_fullctl.task",),
            managers=[
                ("handleref", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="deviceconfighistory",
            name="error_message",
            field=models.TextField(
                blank=True, help_text="Configuration error", null=True
            ),
        ),
        migrations.AlterField(
            model_name="deviceoperationalstatus",
            name="error_message",
            field=models.TextField(
                blank=True, help_text="Configuration error", null=True
            ),
        ),
    ]
