# Generated by Django 3.2.20 on 2023-09-05 10:58

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_handleref.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_devicectl', '0028_auto_20230824_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRefereeReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', django_handleref.models.CreatedDateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', django_handleref.models.UpdatedDateTimeField(auto_now=True, verbose_name='Updated')),
                ('version', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('pending', 'Pending'), ('deactivated', 'Deactivated'), ('failed', 'Failed'), ('expired', 'Expired')], default='ok', max_length=12)),
                ('report', models.JSONField(help_text='Report contents')),
                ('kind', models.CharField(blank=True, help_text="Report type. For example: 'stacked', 'sequential' etc.", max_length=255, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee_reports', to='django_devicectl.device')),
            ],
            options={
                'verbose_name': 'Device Referee Report',
                'verbose_name_plural': 'Device Referee Reports',
                'db_table': 'devicectl_device_referee_report',
            },
            managers=[
                ('handleref', django.db.models.manager.Manager()),
            ],
        ),
    ]
