# Generated by Django 3.2.23 on 2024-01-31 18:41

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_devicectl", "0029_devicerefereereport"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditCtlIXTrafficProcessed",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_fullctl.task",),
            managers=[
                ("handleref", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="AuditCtlIXTrafficReceived",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_fullctl.task",),
            managers=[
                ("handleref", django.db.models.manager.Manager()),
            ],
        ),
    ]
